name: fooder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  image_field: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  path_provider: ^2.0.15

flutter:
  assets:
    - lib/assets/meal_photos/
    - lib/assets/json/
    - lib/assets/show.jpg
  uses-material-design: true
